### ISSUE TITLE
请求升级建议

### ISSUE THREAD

**Issue by chenyulun** [Jacobax/B450M-MORTAR-MAX-GT740#2]
博主你好
我的设备：微星B450M-MORTAR-MAX+RX470
我现在安装的是卡特琳娜10.15.7+openCore@0.6.1

我想升级系统和升级openCore有什么建议；

我之前的系统有个小毛病，应该是没有定制好USB，导致休眠不能唤醒，一直没有处理，

最近买了一个intel的`AX210` PIC-E网卡 + [itlwm](https://github.com/OpenIntelWireless/itlwm)又想再折腾一次

你有什么好的建议或者意见，期待您的回复和支持

**Comment by jacobax** [comment]
oc版本实在太老了，要升级建议重做efi而不是修改升级
问题太笼统，有时间精力先跟着[oc安装指南](https://dortania.github.io/OpenCore-Install-Guide/)做一遍吧，很完备也容易上手，解决绝大部分问题
这里大佬多解答也热情https://t.me/osx86zh

**Comment by chenyulun** [comment]
用oc-gen-x生成了一个efi加上之前的ACPI，可以启动了，我先把oc升级到了0.7.8，接下来再定制一下USB，和升级11.6.1试试，
